### PR TITLE
ENMeval update

### PR DESCRIPTION
**Pull request by jamiemkass**
ENMeval has the `buildRMM()` function, which makes an RMMS metadata object for the ENMeval output. It was not TRUE before because it was not a "main feature", but as the package automatically runs this function and offers the metadata output with the tuning results, I decided it would be appropriate to turn on "metadata" in the package characteristics.

I also made some plotting changes for the figures in the file "ms_figs.R".

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
Thanks @jamiemkass , but when you modify the main code could you take care to be compliant with linting: https://github.com/sylvainschmitt/sdmverse/actions/runs/9073057084/job/24929558422?pr=41#step:5:15

**Comment by jamiemkass** [comment]
Sorry, just fixed it. Thanks.

**Comment by jamiemkass** [comment]
Some checks are failing because pkgs were recently updated on CRAN. Should I fix these now?

**Comment by sylvainschmitt** [comment]
No I'll fix all errors when merging all the last pull requests, but thanks for the proposition.

**Comment by jamiemkass** [comment]
Hey @hannahlowens, @danlwarren, @adamlilith, @babaknaimi, @ecospat, anyone else able to provide a review? Thanks.

**Comment by danlwarren** [comment]
I'll get it.

**Review by danlwarren — APPROVED** [review]
Looks good to me.

**Comment by sylvainschmitt** [comment]
Thanks @danlwarren , I'll merge it with the others PR at once, as soon as @ecospat is ready.

**Pull request merged**
