### PR TITLE
ecospat update

### PR DESCRIPTION
**Pull request by ecospat**

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
Thanks @ecospat for your update. To help review, can you precise the addition (functions and or new functionality) in terms of:
* data_partitioning: Function(s) to partition data for model evaluation
* mod_tuning: Function(s) to tune models

**Comment by jamiemkass** [comment]
@ecospat Hello again -- can you please specify why you turned on "data_partitioning" and "mod_tuning"? Which functions in your package do these things?

**Comment by sylvainschmitt** [comment]
@ecospat , without further news I will close the PR by the end of the week but feel free to reopen it at any time.

**Comment by ecospat** [comment]
switched tuning to "no"

**Pull request merged**
