### PR TITLE
Submission of sdm and usdm

### PR DESCRIPTION
**Pull request by babaknaimi**

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
@babaknaimi , please add a description of why you answered yes to the different fields.

**Comment by sylvainschmitt** [comment]
Please fix the following:

> -For package usdm, title is defined as 'Uncertainty Analysis for Species Distribution Modelling' but should be defined as 'Uncertainty Analysis for Species Distribution Models' according to CRAN.
-For package sdm, version is defined as '1.1.8' but should be defined as '1.1-8' according to CRAN.
-For package usdm, version is defined as '1.1.19' but should be defined as '1.1-18' according to CRAN.
-For package sdm, description is defined as 'sdm is an object-oriented, reproducible and extensible R platform for species distribution modelling. The sdm package is designed to create a comprehensive modelling and simulation framework that: 1) provides a standardised and unified structure for handling species distributions data and modelling techniques (e.g. a unified interface is used to fit different models offered by different packages); 2) is able to support markedly different

**Comment by sylvainschmitt** [comment]
I'm looking for reviewers: @EduardoArle , @gepinillab , @hannahlowens , @sgvignali, @codelab3 , @adamlilith, @MayaGueguen, @danlwarren , @AMBarbosa , @AndreaSanchezTapia, @danlwarren are you available? Please have a look at the [reviewing guidelines](https://github.com/sylvainschmitt/sdmverse/blob/main/REVIEWING.md). Anyway, wait for @babaknaimi to explain the fields before reviewing.

**Comment by jamiemkass** [comment]
@babaknaimi Can you please post the reasons for the "yes" entries? All we need is the function name(s) that show that particular functionality. As you know the packages much better than us, it'll save us lots of time! Thanks very much.

**Comment by sylvainschmitt** [comment]
@babaknaimi , remove your last commit. You do not have to put the reasons in the yaml file but in this discussion.

**Comment by sylvainschmitt** [comment]
> The sdm package provides a full workflow for SDM that includes data cleaning (occ_cleaning -> yes), supporting data integration when separate spatial data for species and environmental layers are introduced (data_integration -> yes), collinearity check (env_collinearity -> yes), and some environmental data transformation and processing (env_process -> yes). Bias layer can be used for generating background data (bias -> yes; backg_sample -> yes) and the study area can be specified through the mask layer (study_region -> yes). Different data partitioning procedure is supported (data_partitioning -> yes), and it can be used for fitting multiple models (mod_fit -> yes), and generate ensemble prediction (mod_ensemble -> yes), also for model evaluation (mod_evaluate -> yes), for both single and multi-species (mod_multispecies -> yes). It can also be used for prediction and projection (pred_general -> yes; pred_extrapolation -> yes. Some post processing of the results are supported (post-processing -> yes). GUI is included in the package (gui -> yes), and most of the main objects has by a metadata object as part of the main object (metadata -> yes).

> The usdm package is designed for supporting uncertainty analysis in species distribution modelling, support collinearity and environmental process, and some post-processing.

**Comment by sylvainschmitt** [comment]
@babaknaimi  , your contribution can be integrated without further edits. After merging your pull request, you will be added to the repository contributors. Please expect to be contacted for a review request in the future.

**Pull request merged**
