### PR TITLE
Submission of occCite & voluModel

### PR DESCRIPTION
**Pull request by hannahlowens**
This adds occCite, a package incorporated into our upcoming sdm manuscript.

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
Thanks, to help review could you give an example of function in each package when you answered yes to the following fields:

- **occ_acquisition**: Function(s) to download occurrence data (yes/no).
- **metadata**: Function(s) to  record analysis metadata (yes/no)

**Comment by sylvainschmitt** [comment]
@adamlilith , @jamiemkass or @sgvignali, would you be available for review?

**Comment by sylvainschmitt** [comment]
Your package metadta does not follow those on CRAN: https://github.com/sylvainschmitt/sdmverse/actions/runs/4337010302/jobs/7581773965.

Please fix before review.

> -For package occCite, title is defined as 'occCite: Querying and Managing Large Biodiversity Occurrence Datasets' but should be defined as 'Querying and Managing Large Biodiversity Occurrence Datasets' according to CRAN.
> -For package occCite, author is defined as 'Hannah L. Owens, Cory Merow, Brian Maitner, Jamie M. Kass, Vijay Barve, Robert P. Guralnick' but should be defined as 'Hannah L. Owens, Cory Merow, Brian Maitner, Jamie M. Kass, Vijay Barve, Robert P. Guralnick, Damiano Oldoni for rOpenSci, see)' according to CRAN.
> -For package occCite, description is defined as 'Facilitates the gathering of biodiversity occurrence data from disparate sources. Metadata is managed throughout the process to facilitate reporting and enhanced ability to repeat analyses.' but should be defined as 'Facilitates the gathering of biodiversity occurrence data

**Comment by hannahlowens** [comment]
> Thanks, to help review could you give an example of function in each package when you answered yes to the following fields:
> 
>     * **occ_acquisition**: Function(s) to download occurrence data (yes/no).
> 
>     * **metadata**: Function(s) to  record analysis metadata (yes/no)

A simple overview of the package can be found [here](https://docs.ropensci.org/occCite/articles/a_Simple.html).
An overview of the package's more advanced features can be found [here](https://docs.ropensci.org/occCite/articles/b_Advanced.html).

 * **occ_acquisition**
    `occQuery()`: [Function documentation](https://docs.ropensci.org/occCite/reference/occQuery.html)
        Downloads data from GBIF and BIEN metadatabases using a single function.

 * **metadata**
    `occCitation()`: [Function documentation](https://docs.ropensci.org/occCite/reference/occCitation.html)
        Harvests citation information from occurrence downloads gathered using `occQuery()`, returns an `occCiteCitation` object.
    `print()`: [Method documentation](https://docs.ropensci.org/occCite/reference/print.occCiteCitation.html)
        Prints citation `occCiteCitation` objects as formatted, alphabetized citations, including DOIs.

**Comment by hannahlowens** [comment]
> Your package metadta does not follow those on CRAN: https://github.com/sylvainschmitt/sdmverse/actions/runs/4337010302/jobs/7581773965.
> 
> Please fix before review.
> 
> > -For package occCite, title is defined as 'occCite: Querying and Managing Large Biodiversity Occurrence Datasets' but should be defined as 'Querying and Managing Large Biodiversity Occurrence Datasets' according to CRAN.
> > -For package occCite, author is defined as 'Hannah L. Owens, Cory Merow, Brian Maitner, Jamie M. Kass, Vijay Barve, Robert P. Guralnick' but should be defined as 'Hannah L. Owens, Cory Merow, Brian Maitner, Jamie M. Kass, Vijay Barve, Robert P. Guralnick, Damiano Oldoni for rOpenSci, see)' according to CRAN.
> > -For package occCite, description is defined as 'Facilitates the gathering of biodiversity occurrence data from disparate sources. Metadata is managed throughout the process to facilitate reporting and enhanced ability to repeat analyses.' but should be defined as 'Facilitates the gathering of biodiversity occurrence data

Ok, I _think_ I've been able to change the submission. Let me know if it went wrong and isn't showing up. I changed the title as requested. I added "Damiano Oldoni for rOpenSci" to the author list, but excluded ", see)" since that appears to be an automatic error. I did not change the description, as again this appears to be an automated error--the version I submitted is the full description from the DESCRIPTION file. The version in the change request is only the first line.

**Comment by sylvainschmitt** [comment]
Ok I fixed the issue for the description coming from my function checking metadata. Now all automatic tests are good. Could you add an example of function in voluModel when you answered yes to the fields for review?

**Comment by hannahlowens** [comment]
> Ok I fixed the issue for the description coming from my function checking metadata. Now all automatic tests are good. Could you add an example of function in voluModel when you answered yes to the fields for review?

Introductory overview: [Intro Vignette](https://hannahlowens.github.io/voluModel/articles/a_Introduction.html)
Example of GLM workflow with package: [GLM Vignette](https://hannahlowens.github.io/voluModel/articles/e_GLMWorkflow.html)

 * **occ_cleaning**
    `downsample()`: [Function documentation](https://hannahlowens.github.io/voluModel/reference/downsample.html)
        Reduces number of occurrences to resolution of input raster.

 * **env_process**
    `bottomRaster()`: [Function documentation](https://hannahlowens.github.io/voluModel/reference/bottomRaster.html)
        Samples deepest depth values from a SpatialPointsDataFrame and generates a RasterLayer.

    `interpolateRaster()`: [Function documentation](https://hannahlowens.github.io/voluModel/reference/interpolateRaster.html)
        Uses thin plate spline regression from fields package to interpolate missing two-dimensional raster values.

    `smoothRaster()`: [Function documentation](https://hannahlowens.github.io/voluModel/reference/smoothRaster.html)
        ses thin plate spline regression from fields package to smooth raster values.

 * **study_region**
    `marineBackground()`: [Function documentation](https://hannahlowens.github.io/voluModel/reference/marineBackground.html)
        Automatically generates background shapefiles for sampling pseudoabsences and/or background points for niche modeling or species distribution modeling. The function is especially useful in cases where one wants to automatically generate training regions that overlap the international date line. Regions that exceed the line are cut and pasted into the appropriate hemisphere instead of being deleted. 

 * **backg_sample**
    `mSampling2D()`: [Function documentation](https://hannahlowens.github.io/voluModel/reference/mSampling2D.html)
        Samples in 2D from background region delimited by shapefile at resolution of raster, automatically removing occurrence points.

    `mSampling3D()`: [Function documentation](https://hannahlowens.github.io/voluModel/reference/mSampling3D.html)
        Samples in 3D from background region delimited by shapefile at resolution of raster, automatically removing occurrence points.

 * **pred_extrapolation**
    `mess3D()`: [Function documentation](https://hannahlowens.github.io/voluModel/reference/MESS3D.html)
        Calculates 3D multivariate environmental similarity surface based on model calibration and projection data.

 * **pred_inspect**
    `plotLayers()`: [Function documentation](https://hannahlowens.github.io/voluModel/reference/plotLayers.html)
        Plots a semitransparent layer of suitable habitat for each depth layer. The redder the color, the shallower the layer, the bluer, the deeper. The more saturated the color, the more layers with suitable habitat.

**Review by sylvainschmitt — APPROVED** [review]

**Comment by sylvainschmitt** [comment]
Thank you for all the information, as you described everything in details I'll accept your submission without second review. After merging your pull request I'll add yo to repository contributors and I'll probably ask you for review when I have new submission. Best, Sylvain

**Comment by hannahlowens** [comment]
> Thank you for all the information, as you described everything in details I'll accept your submission without second review. After merging your pull request I'll add yo to repository contributors and I'll probably ask you for review when I have new submission. Best, Sylvain

Great, thanks! Can do.

**Pull request merged**
