### PR TITLE
Submission of bRacatus

### PR DESCRIPTION
**Pull request by EduardoArle**
Dear Sylvain, 

Thank you for this awesome initiative! I filled in the information about bRacatus, but I am not sure whether the functions I am listing for each functionality are correctly placed, so I provided a short explanation for each of them. Also, RStudio did not allow me to save the file as .yaml, saving it as .yml instead. Please, let me know if there are needed changes. 

Warm regards,
Edu

**occ_acquisition** 

getOcc: downloads GBIF occurrences for the focus species.

(There are two functions that download checklist information, I am not sure if it is relevant to mention them here)

giftRegions: downloads checklists for the plant species in the database Global Inventory of Floras and Traits
glonafRegions: downloads checklists for the plant species in the database Global Naturalized Alien Flora

**occ_cleaning**
**data_integration**

(Those functions don't do the cleaning itself, instead they provide an assessment from 0 to 1 of either the accuracy or the biogeographical status of each data point, based on range map or checklist information. The user can filter or classify the data based on this information. I see it more as data integration than data cleaning)

accuracy: estimates the accuracy of each point record.
biogeoStatus :estimates the biogeographical status of each point record.

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
@adamlilith , @jamiemkass or @sgvignali, would you be available for review?

**Comment by sylvainschmitt** [comment]
Automatic testing failed, please change your `.yml` by `.yaml` as instructed in contribution guidelines.

**Comment by sylvainschmitt** [comment]
I fixed your yaml using the correct extension and defining line 37 as a string using quotes. Anyway your information are not right and did not match CRAN:

https://github.com/sylvainschmitt/sdmverse/actions/runs/4341841359/jobs/7581929898

> -For package bRacatus, title is defined as 'A Method to Estimate the Accuracy and Biogeographical Status of Georeferenced Biological Data' but should be defined as 'A Method to Estimate the Accuracy and Biogeographical Status of
> Georeferenced Biological Data' according to CRAN.
> -For package bRacatus, description is defined as 'Automated assessment of accuracy and geographical status of georeferenced biological data. The methods rely on reference regions, namely checklists and range maps. Includes functions to obtain data from the Global Biodiversity Information Facility <https://www.gbif.org/> and from the Global Inventory of Floras and Traits <https://gift.uni-goettingen.de/home>. Alternatively, the user can input their own data. Furthermore, provides easy visualisation of the data and the results through the plotting functions. Especially suited for large datasets.' but should be defined as 'Automated assessment of accuracy and geographical status of georeferenced biologica

**Comment by EduardoArle** [comment]
Hi Sylvain,

I apologise for the errors in my submission. I don't understand why it is saying that the info does not match CRAN. I copied and pasted from there...

'title is defined as 'A Method to Estimate the Accuracy and Biogeographical Status of Georeferenced Biological Data' but should be defined as 'A Method to Estimate the Accuracy and Biogeographical Status of
Georeferenced Biological Data' according to CRAN.'

Should I fill it in again?

Cheers,
Eduardo



**********************************************************************************

Eduardo Arlé

Azrieli International Postdoctoral Research Fellow
The Belmaker Lab - Marine Ecology and Biodiversity
School of Zoology
Tel Aviv University

*Please, note that my working days are from Sunday to Thursday.


________________________________

**Comment by sylvainschmitt** [comment]
Ok for the title but the description is wrong and should be: "Automated assessment of accuracy and geographical status of georeferenced biological data. The methods rely on reference regions, namely checklists and range maps. Includes functions to obtain data from the Global Biodiversity Information Facility <https://www.gbif.org/> and from the Global Inventory of Floras and Traits <https://gift.uni-goettingen.de/home>. Alternatively, the user can input their own data. Furthermore, provides easy visualisation of the data and the results through the plotting functions. Especially suited for large datasets. The reference for the methodology is: Arlé et al. (under review)."

**Comment by sylvainschmitt** [comment]
Anyway, I'll fix it.

**Review by sylvainschmitt — APPROVED** [review]
Ok all information seems good to me. I'll let @adamlilith , @jamiemkass or @sgvignali validate but as far as I'm concerned you are good to go. I will probably ask you as a reviewer for future submissions.

**Pull request merged**
