### PR TITLE
Submission of enmSdmX

### PR DESCRIPTION
**Pull request by adamlilith**
Added all required fields for enmSdmX. Functions for that pertain to fields for which I selected "yes":

bias:
* weightByDist: Calculates weights for points based on proximity to other points and the distance of spatial autocorrelation as per the "inverse-p" weighting method; Stolar & Nielsen 2015 Diversity and Distributions 21:595-608)
* geoThin: Thin geographic points deterministically or randomly

data_partitioning:
* geoFold: Create mutually-exclusive geographic partitions based on spatial clumps in presences

mod_fit:
* trainBRT, trainGAM, trainGLM, trainMaxEnt, trainMaxNet, trainNS, trainRF: Each functions conducts a grid search across a suite of tuning parameters.
* trainByCrossValid and summaryByCrossValid: Use one of the trainXYZ functions in a data-partitioned procedure to fit the respective model

mod_tuning: (As model_fit).

mod_evaluate:
* evalAUC, evalContBoyce, evalMultiAUC, evalThreshold, evalThresholdStats: Calculate AUC, CBI, etc. The primary difference between these functions and those in other packages is that these allow for site-level weights (e.g., to cancel bias).

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
Hi Adam and thanks for the submission. The yaml format is strict you need to avoid spaces before `:`

> Error in yaml.load(string, error.label = error.label, ...) : 
  (/home/runner/work/_temp/Library/sdmverse/extdata/packages/enmSdmX.yaml) Parser error: while parsing a block mapping at line 1, column 1 did not find expected key at line 8, column 189

**Comment by sylvainschmitt** [comment]
I'm looking for reviewers: @EduardoArle , @gepinillab , @hannahlowens , @jamiemkass , @sgvignali are you available? Please have a look at the [reviewing guidelines](https://github.com/sylvainschmitt/sdmverse/blob/main/REVIEWING.md)

**Review by sylvainschmitt — APPROVED** [review]
Congrats everything seems good. I'll wait for the automatic check validation and if possible for a second reviewer. But as far as I'm concerned `enmSdmX` is good to go.

**Comment by sylvainschmitt** [comment]
There are other issues with the yaml:

- you should escape the `"` in the yaml field with `\"`
- maintainer should be defined as 'Adam B. Smith <adam.smith@mobot.org>'

**Comment by sylvainschmitt** [comment]
Okay to go forward and as your submission is pretty clear I wont ask additional reviewers. Your contribution can be integrated without further edits. After merging your pull request, you will be added to the repository contributors. Please expect to be contacted for a review request in the future.

**Comment by adamlilith** [comment]
Thanks, @sylvainschmitt!  And please do assign me reviews for other packages.

**Pull request merged**
