### PR TITLE
biomod2 submission

### PR DESCRIPTION
**Pull request by MayaGueguen**
Hello there,

Thank you for the nice shiny app and the management :pray: 
Here is the fork containing the `yaml` file for `biomod2` package.

Please do not hesitate if we missed / misunderstood something !

Maya & Rémi

- **bias:** `BIOMOD_Modeling`, `bm_CrossValidation`
- **backg_sample:** `BIOMOD_FormatingData`, `bm_PseudoAbsences`
- **data_partitioning:** `BIOMOD_Modeling`, `bm_CrossValidation`
- **mod_fit:** `BIOMOD_Modeling`, `BIOMOD_ModelingOptions`
- **mod_tuning:** `BIOMOD_Tuning`
- **mod_ensemble:** `BIOMOD_EnsembleModeling`
- **mod_evaluate:** `BIOMOD_Modeling`, `BIOMOD_EnsembleModeling`, `bm_FindOptimStat`
- **pred_general:** `BIOMOD_Projection`, `BIOMOD_EnsembleForecasting`
- **pred_extrapolation:** `BIOMOD_Projection`
- **pred_inspect:** `bm_VariablesImportance`, `bm_PlotEvalMean`, `bm_PlotEvalBoxplot`, `bm_PlotVarImpBoxplot`, `bm_PlotResponseCurves`
- **post_processing:** `BIOMOD_RangeSize`, `bm_BinaryTransformation`

Short description of main functions : 

- `BIOMOD_FormatingData` : gathers together all input data needed (_xy, presences/absences, explanatory variables, and the same for evaluation data if available_) to run `biomod2` models. It allows to select pseudo-absences if no absence data is available, with different strategies
- `BIOMOD_ModelingOptions` : set biomod2 single models parameters
- `BIOMOD_Tuning` : tune biomod2 single models parameters
- `BIOMOD_Modeling` : calibrate and evaluate a range of modeling techniques for a given species distribution. The dataset can be split up in calibration/validation parts, and the predictive power of the different models can be estimated using a range of evaluation metrics
- `BIOMOD_EnsembleModeling` : combine a range of models built with the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function in one (or several) ensemble model. Modeling uncertainty can be assessed as well as variables importance, ensemble predictions can be evaluated against original data, and created ensemble models can be projected over new conditions
- `BIOMOD_Projection` : project a range of models built with the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function onto new environmental data (_which can represent new areas, resolution or time scales for example_)
- `BIOMOD_EnsembleForecasting` : project ensemble models built with the [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) function onto new environmental data (_which can represent new areas, resolution or time scales for example_)
- `BIOMOD_RangeSize` : calculate the absolute number of locations (pixels) lost, stable and gained, as well as the corresponding relative proportions, between two (or more) binary projections of (ensemble) species distribution models (_which can represent new time scales or environmental scenarios for example_)

Short description of secundary functions : 

- `bm_PseudoAbsences` : select pseudo-absences according to 4 different methods : random, sre, disk or user.defined
- `bm_CrossValidation` : 
- `bm_FindOptimStat` : find the threshold to convert continuous values into binary ones leading to the best score for a given evaluation metric
- `bm_BinaryTransformation` : convert probability (not necessary between 0 and 1) values into binary presence-absence (0 or 1) values according to a predefined threshold 
- `bm_VariablesImportance` : compute a variable importance value for each variable involved in the given model
- `bm_PlotEvalMean` : represents mean evaluation scores (and their standard deviation) of species distribution models, from [BIOMOD.models.out](https://biomodhub.github.io/biomod2/reference/BIOMOD.models.out.html) or [BIOMOD.ensemble.models.out](https://biomodhub.github.io/biomod2/reference/BIOMOD.ensemble.models.out.html) objects that can be obtained from [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) or [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) functions. Scores are represented according to 2 different evaluation methods, and models can be grouped
- `bm_PlotEvalBoxplot` : represents boxplot of evaluation scores of species distribution models, from [BIOMOD.models.out](https://biomodhub.github.io/biomod2/reference/BIOMOD.models.out.html) or [BIOMOD.ensemble.models.out](https://biomodhub.github.io/biomod2/reference/BIOMOD.ensemble.models.out.html) objects that can be obtained from [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) or [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) functions. Scores are represented according to 2 grouping methods
- `bm_PlotVarImpBoxplot` : represents boxplot of variables importance of species distribution models, from [BIOMOD.models.out](https://biomodhub.github.io/biomod2/reference/BIOMOD.models.out.html) or [BIOMOD.ensemble.models.out](https://biomodhub.github.io/biomod2/reference/BIOMOD.ensemble.models.out.html) objects that can be obtained from [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) or [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) functions. Scores are represented according to 3 grouping methods
- `bm_PlotResponseCurves` : represents response curves of species distribution models, from [BIOMOD.models.out](https://biomodhub.github.io/biomod2/reference/BIOMOD.models.out.html) or [BIOMOD.ensemble.models.out](https://biomodhub.github.io/biomod2/reference/BIOMOD.ensemble.models.out.html) objects that can be obtained from [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) or [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) functions. Response curves can be represented in either 2 or 3 dimensions

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
@MayaGueguen , thanks for your submission. Can you fix the following [issues](https://github.com/sylvainschmitt/sdmverse/actions/runs/4564530619/jobs/8054495394?pr=15):

> Error in sdmverse::check_cran_metadata() : 
-For package biomod2, version is defined as '4.2-3' but should be defined as '4.2-2' according to CRAN.
-For package biomod2, author is defined as 'Wilfried Thuiller, Damien Georges, Maya Guéguen, Rémi Patin, Robin Engler, Frank Breiner, Bruno Lafourcade' but should be defined as 'Wilfried Thuiller, Damien Georges, Maya Gueguen, Robin Engler, Frank Breiner, Bruno Lafourcade, Remi Patin' according to CRAN.
-For package biomod2, maintainer is defined as 'Maya Guéguen <maya.gueguen@univ-grenoble-alpes.fr>' but should be defined as 'Maya Gueguen <maya.gueguen@univ-grenoble-alpes.fr>' according to CRAN.
-For package biomod2, description is defined as 'Functions for species distribution modeling, calibration and evaluation, ensemble of models, ensemble forecasting and visualization. The package permits to run consistently up to 11 single models on a presence/absences (resp presences/pseudo-absences) dataset and to combine them in ensemble models and ensemble projections. Some be

**Comment by MayaGueguen** [comment]
Sure, it's done. But this is likely to change in near future then :sun_with_face:

**Comment by sylvainschmitt** [comment]
> Sure, it's done. But this is likely to change in near future then sun_with_face

Thanks, and okay. But the nice thing about the package is that the function `check_cran_metadata` check already accepted packages at the same time. So if somebody submit a package (or any modification on the repository) will result in a notification of CRAN metadata changes in biomod2.

**Comment by sylvainschmitt** [comment]
I'm looking for reviewers: @EduardoArle , @gepinillab , @hannahlowens , @jamiemkass , @sgvignali, @codelab3 , @adamlilith  are you available? Please have a look at the [reviewing guidelines](https://github.com/sylvainschmitt/sdmverse/blob/main/REVIEWING.md)

**Review by sylvainschmitt — APPROVED** [review]
Thanks for the metadata, everything is good, and thanks for the nice explanations about the functions. I'll let time for somebody else to review, but if anybody react I'll accept your PR.

**Comment by sgvignali** [comment]
Do you still need the review? I would have time now

**Comment by sylvainschmitt** [comment]
> Do you still need the review? I would have time now

Yes please, it does not feel right if I'm the only reviewer.

**Comment by sgvignali** [comment]
I don't see the button "add your review"

**Comment by sylvainschmitt** [comment]
Please go in Files changed:
image
Then add a comment on any line by clicking on it, and choose "Start a review":
image
Finally when you are finished use the button review changes, leave a final comment, and make your decision, before submitting your review:
image

**Comment by sylvainschmitt** [comment]
I'm considering developing a wiki to better help submission and reviewing processes.

**Comment by hannahlowens** [comment]
This link could help, RE: code review: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request

**Review by sgvignali — APPROVED** [review]
It looks ok

**Comment by sgvignali** [comment]
There was actually a notification on the top of the page with the button to start the review!

**Comment by sylvainschmitt** [comment]
@MayaGueguen, our contribution can be integrated without further edits. After merging your pull request, you will be added to the repository contributors. Please expect to be contacted for a review request in the future.

**Pull request merged**
