### PR TITLE
Update voluModel.yml

### PR DESCRIPTION
**Pull request by hannahlowens**
Changed coding to TRUE/FALSE, verified coding was correct.

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
@hannahlowens , why did you changed to TRUE / FALSE ? The yes / no was okay and I think more humanly readable.

**Comment by hannahlowens** [comment]
> @hannahlowens , why did you changed to TRUE / FALSE ? The yes / no was okay and I think more humanly readable.

In the email from @jamiemkass, he says "A reminder to everyone -- if you haven't already, please go over the attributes of your package once more in sdmverse and make sure that all the right categories are labeled TRUE. Again, we are now labeling categories as TRUE if you can demonstrate that your package addresses it with at least one function." Correspondingly, I changed "no" to "FALSE". Did I misunderstand?

**Comment by sylvainschmitt** [comment]
Ah ok, @jamiemkass mail was unclear. In yaml you can use either TRUE / FALSE or yes / no. I think what Jamie meant is to update the functionalities of your package metadata if needed.

**Comment by sylvainschmitt** [comment]
So if that's okay to you @hannahlowens I'll reject your two pull requests. Unless you changes something else than yes by TRUE and no by FALSE.

**Comment by hannahlowens** [comment]
> So if that's okay to you @hannahlowens I'll reject your two pull requests. Unless you changes something else than yes by TRUE and no by FALSE.

Yep, no problem. Nothing else changed.

**Pull request closed without merging**
