### PR TITLE
Submission of rangeModelMetadata

### PR DESCRIPTION
**Pull request by jamiemkass**
Added an entry for rangeModelMetadata.

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
Please described your reasons for answering yes to the fields. 

I'm looking for reviewers: @EduardoArle , @gepinillab , @hannahlowens , @jamiemkass , @sgvignali, @codelab3 , @adamlilith; @MayaGueguen are you available? Please have a look at the [reviewing guidelines](https://github.com/sylvainschmitt/sdmverse/blob/main/REVIEWING.md)

**Comment by sylvainschmitt** [comment]
Please fix the following:

> -For package rangeModelMetadata, author is defined as 'Cory Merow, Brian Maitner, Hannah L. Owens, Jamie M. Kass, Brian Enquist, Rob Guralnik, Damaris Zurell, Christian Koenig' but should be defined as 'Cory Merow, Brian Maitner, Hannah Owens, Jamie Kass, Brian Enquist, Rob Guralnik, Damaris Zurrell, Christian Koenig' according to CRAN.

**Comment by jamiemkass** [comment]
Having a similar problem here because I fixed Damaris' last name but it's
wrong on CRAN. Should I turn the cran field off here?

**Comment by jamiemkass** [comment]
Okay, turned off cran and now the checks have passed.

**Comment by sylvainschmitt** [comment]
Okay but ideally when  it's fixed on CRAN we should put back cran to yes.

**Comment by jamiemkass** [comment]
Explanations: It's a package for generating SDM metadata, so metadata is "yes", and it also has a shiny app, so "yes" for GUI.

**Comment by sylvainschmitt** [comment]
> Explanations: It's a package for generating SDM metadata, so metadata is "yes", and it also has a shiny app, so "yes" for GUI.

Ok this is simple enough for me to review alone I think. Your contribution can be integrated without further edits.

**Review by sylvainschmitt — APPROVED** [review]

**Pull request merged**
