### PR TITLE
flexsdm update

### PR DESCRIPTION
**Pull request by sjevelazco**

### CODE REVIEW

**Comment by sylvainschmitt** [comment]
Update of #3 , see also #34 .

**Comment by sylvainschmitt** [comment]
As the only change is the addition of bias discussed extensively by mail I suggest directly accepting the pull request, do you agree @hannahlowens as reviewer of the first submission?

**Review by sylvainschmitt — APPROVED** [review]

**Comment by jamiemkass** [comment]
@hannahlowens Just checking -- do you agree with Sylvain's assessment?

**Review by hannahlowens — APPROVED** [review]
This looks good to me.

**Comment by sylvainschmitt** [comment]
Great, thanks @hannahlowens

**Pull request merged**
